apply plugin: 'com.android.library'

android {
    namespace 'com.arthenica.ffmpegkit'
    compileSdk 36
    ndkVersion "26.1.10909125"

    defaultConfig {
        minSdk 24
        targetSdk 36
        versionCode 240600
        versionName "6.0"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ["../libs"]
        }
    }

    publishing {
        singleVariant('release') {
            withJavadocJar()
            withSourcesJar()
        }
    }
}

dependencies {
    api 'com.arthenica:smart-exception-java:0.2.1'
}
